name: Delete development releases

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  delete-pr-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Delete development releases whose branches no longer exist
        run: .github/bin/delete-dev-releases
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
